name: âš™ï¸ CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ğŸš¦ Lint
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: ğŸ“¥ Install dependencies
        run: cd app && npm ci

      - name: ğŸ” Run linter
        run: cd app && npm run lint

  typecheck:
    name: ğŸ‘®â€â™‚ï¸ Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ“¥ Install dependencies
        run: cd app && npm ci

      - name: ğŸš¦ Run typecheck
        run: cd app && npm run typecheck
